harnessApiVersion: '1.0'
type: ROLLING
concurrencyStrategy: INFRA
envName: Lab 2 Production Environment
failureStrategies:
- executionScope: WORKFLOW
  failureTypes:
  - APPLICATION_ERROR
  repairActionCode: ROLLBACK_WORKFLOW
  retryCount: 0
notificationRules:
- conditions:
  - FAILED
  executionScope: WORKFLOW
  notificationGroupAsExpression: false
  userGroupAsExpression: false
  userGroupIds:
  - PFIVcv84TVW6OEpQEDvmGw
phases:
- type: KUBERNETES
  computeProviderName: odievich-k8s-hyperv-minikube
  daemonSet: false
  infraDefinitionName: Lab 2 Prometheus
  name: Rolling
  phaseSteps:
  - type: K8S_PHASE_STEP
    name: Deploy
    steps:
    - type: K8S_DEPLOYMENT_ROLLING
      name: Rollout Deployment
    stepsInParallel: false
  - type: K8S_PHASE_STEP
    name: Verify
    stepsInParallel: false
  - type: K8S_PHASE_STEP
    name: Wrap Up
    stepsInParallel: false
  provisionNodes: false
  serviceName: prometheus
  statefulSet: false
rollbackPhases:
- type: KUBERNETES
  computeProviderName: odievich-k8s-hyperv-minikube
  daemonSet: false
  infraDefinitionName: Lab 2 Prometheus
  name: Rollback Rolling
  phaseNameForRollback: Rolling
  phaseSteps:
  - type: K8S_PHASE_STEP
    name: Deploy
    phaseStepNameForRollback: Deploy
    statusForRollback: SUCCESS
    steps:
    - type: K8S_DEPLOYMENT_ROLLING_ROLLBACK
      name: Rollback Deployment
    stepsInParallel: false
  - type: K8S_PHASE_STEP
    name: Wrap Up
    phaseStepNameForRollback: Wrap Up
    stepsInParallel: false
  provisionNodes: false
  serviceName: prometheus
  statefulSet: false
templatized: true
userVariables:
- type: TEXT
  fixed: false
  mandatory: false
  name: verify_canary
  value: 'yes'
- type: TEXT
  fixed: false
  mandatory: false
  name: metric_verification
  value: Prometheus
